### ISSUE TITLE
Maven wrapper can be added to simplify the usage 

### ISSUE THREAD

**Issue by KeenWarrior** [vert-x3/vertx-maven-starter#1]
Like in vertx-gradle-starter this project can also use a wrapper so that it is easy to begin with without setting up maven.

**Comment by KeenWarrior** [comment]
I would like to work on this issue.

**Comment by cescoffier** [comment]
Great, contributions are welcome!

**Comment by vietj** [comment]
@KeenWarrior any news about it ?

**Comment by adietish** [comment]
@vietj It looks like this issue can be closed, given that the PR for it was merged?
