### ISSUE TITLE
netty connection refused

### ISSUE THREAD

**Issue by sangmoon** [vert-x3/vertx-maven-starter#6]
Hi. I 'm new on vertx.
I start from starter project, when testing or running application, got an error.
Main code is the just same  as the default. 

```
$ mvn clean packge

// ... 

Running io.vertx.starter.MainVerticleTest
Nov 30, 2018 1:05:26 PM io.vertx.core.http.impl.HttpClientRequestImpl
SEVERE: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
```

jdk  1.8.0_172-b11
OS macOS high sierra 10.13.6

 thank you.

**Comment by sangmoon** [comment]
sorry, it's my mistake.
I made another start method in MainVerticle.java.
Removing it, it works.

**Comment by venkatish** [comment]
Hi 
I am also facing the same issue. Can you please provide me the start up script.
