### ISSUE TITLE
is this update to date?

### ISSUE THREAD

**Issue by ORESoftware** [vert-x3/vertx-maven-starter#7]
I am looking to get started with vertx, for a simple API server...which repo should I clone..this one?

**Comment by ORESoftware** [comment]
cloned this and it seemed to work fine, not sure how the deps in pom.xml stay up to date though? since the repo doesn't seem to have change in at least 18 months. Anyway, just looking for a good ORM for Vertx if you have any recommendations on how to use Vertx with Postgres or MySQL thanks!

**Comment by cescoffier** [comment]
It's been updated 22 days ago, which is not too bad. However, you are right, it should be updated to 3.6.2.

**Comment by cescoffier** [comment]
It has been updated to 3.6.3

**Comment by ORESoftware** [comment]
awesome thx
